name: motsart
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - numpy
  - scipy
  - matplotlib
  - pandas
  - rdkit
  - tqdm
  - xtb
  - ase
  - qcelemental
  - pip:
    - hydra-zen
    - wandb
    - pymatgen
    - einops
    - rich
    - graphrc
    - racerts
